name: CI
on: push
jobs:
  build-project:
    name: Build_Project
    runs-on: ubuntu-latest
    steps:
    - name: install
      uses: actions/checkout@v3
    - name: Create word.txt 
      run: mkdir -p path/to/artifact
    - name: Create word.txt2
      run: echo hello > path/to/artifact/world.txt
    - name: Upload   
      uses: actions/upload-artifact@v3
      with:
       name: my-artifact
       path: path/to/artifact/world.txt
  
  release-project:
    name: Release Project
    runs-on: ubuntu-latest
    needs: build-project
    steps:
    - name: Download arifact
      uses: actions/download-artifact@v3
      with:
        name: my-artifact
    - name: Display structure of downloaded files
      run: ls -R
    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.run_number}}
        release_name: Release ${{ github.run_number }}
