name: CI
on: push
jobs:
  build-project:
    name: First
    runs-on: ubuntu-latest
    steps:
    - name: install
      uses: actions/checkout@v3
    - name: Create word.txt 
      run: mkdir -p path/to/artifact
    - name: Create word.txt2
      run: echo hello > path/to/artifact/world.txt
    - name: Upload   
      uses: actions/upload-artifact@v3
      with:
       path: world.txt
